import 'package:flutter/material.dart';
import '../../system_admin/views/widgets/admin_scaffold.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return AdminScaffold(
      title: 'Privacy Policy',
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 800),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Privacy Policy',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 8),
              const Text(
                'Last updated: July 13, 2026',
                style: TextStyle(fontSize: 14, color: Colors.grey),
              ),
              const SizedBox(height: 24),
              _buildSection(
                'Introduction',
                'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\nAwehBiz is a cloud-based mobile application designed for small traders to manage Point of Sale (POS), Inventory Control, and Analytics. We use Your Personal Data to provide and improve this Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
              ),
              _buildSection(
                'Interpretation and Definitions',
                '**Interpretation**\nThe words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\n**Definitions**\nFor the purposes of this Privacy Policy:\n• **Account** means a unique account created for You to access our Service or parts of our Service.\n• **Affiliate** means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n• **Application** refers to AwehBiz, the software program provided by the Company.\n• **Company** (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to SmartBuilders (Pty) Ltd, 63 Ilchester Avenue, Somerset Park Umhlanga, 4319.\n• **Country** refers to: South Africa\n• **Device** means any device that can access the Service such as a computer, a cell phone or a digital tablet.\n• **Personal Data** (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.\n• **Service** refers to the Application.\n• **Service Provider** means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n• **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n• **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
              ),
              _buildSection(
                'Collecting and Using Your Personal Data',
                '**Types of Data Collected**\n\n**Personal Data**\nWhile using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n• Email address\n• First name and last name\n• Phone number\n• Address, State, Province, ZIP/Postal code, City\n• Bank Account Number and Banking Details (collected to set up payment processing and to verify business legitimacy).\n\n**Usage Data**\nUsage Data is collected automatically when using the Service.\nUsage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device\'s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\nWe may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.\n\n**Information Collected while Using the Application**\nWhile using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:\n• Pictures and other information from your Device\'s camera and photo library (e.g., for scanning barcodes or uploading product images).\n\nWe use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and/or a Service Provider\'s server or it may be simply stored on Your device.\n\nYou can enable or disable access to this information at any time, through Your Device settings.',
              ),
              _buildSection(
                'Use of Your Personal Data',
                'The Company may use Personal Data for the following purposes:\n• To provide and maintain our Service, including to monitor the usage of our Service.\n• To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.\n• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.\n• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.\n• To provide You with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.\n• To manage Your requests: To attend and manage Your requests to Us.\n• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve Our Service, products, services, marketing and your experience.\n• To prevent misuse of services: We collect and process banking details and business information to verify the identity of businesses and to ensure that users do not abuse the 30-day free trial period or violate our Terms of Service.\n\nWe may share Your Personal Data in the following situations:\n• With Service Providers: We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.\n• For business transfers: We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.\n• With Affiliates: We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.\n• With business partners: We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.\n• With other users: If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.\n• With Your consent: We may disclose Your Personal Data for any other purpose with Your consent.',
              ),
              _buildSection(
                'Retention of Your Personal Data',
                'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\nWhere possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods ("up to") and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:\n\n**Account Information**\n• User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.\n\n**Customer Support Data**\n• Support tickets and correspondence: up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims\n• Chat transcripts: up to 24 months for quality assurance and staff training purposes.\n\n**Usage Data**\n• Application usage statistics: up to 24 months to understand feature adoption and service improvements.\n• Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.\n\nUsage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.\n\nWe may retain Personal Data beyond the periods stated above for different reasons:\n• Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).\n• Legal claims: Data is necessary to establish, exercise, or defend legal claims.\n• Your explicit request: You ask Us to retain specific information.\n• Technical limitations: Data exists in backup systems that are scheduled for routine deletion.\n\nYou may request information about how long We will retain Your Personal Data by contacting Us.\n\nWhen retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:\n• Deletion: Personal Data is removed from Our systems and no longer actively processed.\n• Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.\n• Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.',
              ),
              _buildSection(
                'Transfer of Your Personal Data',
                'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to --- and maintained on --- computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.\n\nWhere required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
              ),
              _buildSection(
                'Delete Your Personal Data',
                'You have the right to delete or request that We assist in deleting Your Personal Data that We have collected about You.\n\nOur Service may give You the ability to delete certain information about You from within the Service.\n\nYou may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.\n\nPlease note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.',
              ),
              _buildSection(
                'Disclosure of Your Personal Data',
                '**Business Transactions**\nIf the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\n**Law enforcement**\nUnder certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).\n\n**Other legal requirements**\nThe Company may disclose Your Personal Data in the good faith belief that such action is necessary to:\n• Comply with a legal obligation\n• Protect and defend the rights or property of the Company\n• Prevent or investigate possible wrongdoing in connection with the Service\n• Protect the personal safety of Users of the Service or the public\n• Protect against legal liability',
              ),
              _buildSection(
                'Security of Your Personal Data',
                'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.',
              ),
              _buildSection(
                'Children\'s Privacy',
                'Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.\n\nIf We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent\'s consent before We collect and use that information.',
              ),
              _buildSection(
                'Service Plans and Features',
                'The AwehBiz Application offers two primary service plans: Basic and Premium.\n\n• Basic Plan (R300 p/m):\n  o Setup is free.\n  o Features include Barcode Scanner Access, Low-stock Alerts, Cash Sales, up to 50 Card Payments Daily, Net Profit + Analytics, up to 100 Products, and 15 Services.\n\n• Premium Plan (R500 p/m):\n  o Setup is free.\n  o Features include Barcode Scanner Access, Unlimited Card Payments, Daily Breakdown of Products Sold, Full Insights, Unlimited Fixed Expenses, and Unlimited Products and Services.\n  o A 30-day free trial of the Premium Tier is available to all new users.\n\nWe may collect and verify Your banking details and business information to authenticate Your business, set up payment processing for card transactions, and to prevent the misuse of the 30-day free trial and other promotional offers.',
              ),
              _buildSection(
                'Links to Other Websites',
                'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.\n\nWe have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
              ),
              _buildSection(
                'Changes to this Privacy Policy',
                'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\nWe will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.\n\nYou are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
              ),
              _buildSection(
                'Contact Us',
                'If you have any questions about this Privacy Policy, You can contact us:\n• By email: info@smart-builders.co.za\n• By visiting this page on our website: https://www.smart-builders.co.za/',
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: const TextStyle(fontSize: 14, height: 1.5),
          ),
        ],
      ),
    );
  }
}
