// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Returns the Firebase configuration that matches the platform currently
  // running the app, such as Android, web, iOS, macOS, or Windows.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web Firebase configuration used when running in a browser.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlIOb5gN2T2B0N9IhiSNCK6mFjLie1q8',
    appId: '1:919993307286:web:2d589beec2ae2f32b832b7',
    messagingSenderId: '919993307286',
    projectId: 'awehpay',
    authDomain: 'awehpay.firebaseapp.com',
    storageBucket: 'awehpay.firebasestorage.app',
    measurementId: 'G-D05HVL9XJH',
  );

  // Android Firebase configuration used by the emulator or Android devices.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yLQIHAI123Tg_Z_qdD7VPhROudt2z8Y',
    appId: '1:919993307286:android:aea5c3b7e3b8922cb832b7',
    messagingSenderId: '919993307286',
    projectId: 'awehpay',
    storageBucket: 'awehpay.firebasestorage.app',
  );

  // iOS Firebase configuration used when running on iPhone or iPad.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIo4MdT_1f9Eif5G1ArsGHLiaXOzWXgk8',
    appId: '1:919993307286:ios:388f5c1b24168e9cb832b7',
    messagingSenderId: '919993307286',
    projectId: 'awehpay',
    storageBucket: 'awehpay.firebasestorage.app',
    iosBundleId: 'com.example.awePay',
  );

  // macOS Firebase configuration used by the desktop macOS build.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIo4MdT_1f9Eif5G1ArsGHLiaXOzWXgk8',
    appId: '1:919993307286:ios:388f5c1b24168e9cb832b7',
    messagingSenderId: '919993307286',
    projectId: 'awehpay',
    storageBucket: 'awehpay.firebasestorage.app',
    iosBundleId: 'com.example.awePay',
  );

  // Windows Firebase configuration used by the desktop Windows build.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVlIOb5gN2T2B0N9IhiSNCK6mFjLie1q8',
    appId: '1:919993307286:web:f8d4fea3065b6dceb832b7',
    messagingSenderId: '919993307286',
    projectId: 'awehpay',
    authDomain: 'awehpay.firebaseapp.com',
    storageBucket: 'awehpay.firebasestorage.app',
    measurementId: 'G-YJ80BFVSDL',
  );
}
